@api=http://localhost:4000/users

GET {{api}}


###
POST  {{api}}
Content-Type: application/json

{
    "Nombre":"miriam",
    "correo":"miriam@gmail.com",
    "contraseña":"jabljas"
}

###
GET {{api}}/7

###
DELETE {{api}}/14

###
GET {{api}}/count

###
PUT {{api}}/7
Content-Type:  application/json

{
    "Nombre": "lisa",
    "correo":"erika@gmail.com",
    "contraseña": "1234fuyf"
}